steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/Book-Demo:$SHORT_SHA'
  - '.'
  - '-f'
  - 'Dockerfile'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/book-demo:$SHORT_SHA'
