steps:
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/book-demo:$SHORT_SHA'
  - '.'
  - '-f'
  - 'Dockerfile'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/book-demo:$SHORT_SHA'
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'approve'
  - '$BUILD_ID'
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'book-demo', '--image', 'asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/book-demo:$SHORT_SHA', '--region', 'asia-south1']
images:
- asia-south1-docker.pkg.dev/grafana-monitoring-demo/demo-repo/book-demo:$SHORT_SHA
