name: Java CI with Maven build tool
on:
  workflow_dispatch:
    
jobs:
  build:
      uses: prasadthorati/thymeleafexamples-petclinic/.github/workflows/build.yml@self-hosted
      secrets: 
        ghcr_username: ${{ secrets.GHCR_USERNAME }}
        ghcr_token: ${{ secrets.GHCR_TOKEN }}
